### ISSUE TITLE
It is possible to remove the cancel button

### ISSUE THREAD

**Issue by EmmanuelSkapple** [GA-MO/react-confirm-alert#1]
I need only de accept button, It is possible?

**Comment by GA-MO** [comment]
Thanks for issue.
I have fixed for the issue.
You just remove props that you do not want like this:
`
confirmAlert({
      title: 'Confirm to submit',
      message: 'Are you sure to do this.',
      confirmLabel: 'Confirm',
      onConfirm: () => alert('Action after Confirm')
})
`
