### ISSUE TITLE
Module not found: Error: Cannot resolve module 'imports' in  index.js

### ISSUE THREAD

**Issue by trojanh** [GA-MO/react-confirm-alert#13]
ERROR in ../~/react-confirm-alert/lib/index.js
Module not found: Error: Cannot resolve module 'imports' in /Users/Kiprosh/projects/realvolve/realvolve/node_modules/react-confirm-alert/lib
 @ ../~/react-confirm-alert/lib/index.js 14:13-29

**Comment by GA-MO** [comment]
@trojanh Can you explain?

**Comment by trojanh** [comment]
I get this when I run my application after installing the package.

**Comment by GA-MO** [comment]
@trojanh  Is still has an error in the latest version?
