### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by alexandru-tanasie-clarisoft** [GA-MO/react-confirm-alert#2]
Hi,
I found this  **Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.**  on this package

**Comment by GA-MO** [comment]
I have fixed this **warning**  in `react-confirm-alert@1.0.7`
Thanks a lot to report.

**Comment by alexandru-tanasie-clarisoft** [comment]
Now is working. Thank you for fixed.
