### ISSUE TITLE
whyy always append alert  to body.

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [GA-MO/react-confirm-alert#3]
can we add **id of the parent container** to which the alert should be added to.

createElemetReconfirm -> document.body.appendChild(divTarget);

confirmAlert({
      **parentId: '*******'                                    // some id where should it host**
      title: 'Confirm to submit',                        // Title dialog
      message: 'Are you sure to do this.',               // Message dialog
      childrenElement: () => <div>Custom UI</div>,       // Custom UI or Component
      confirmLabel: 'Confirm',                           // Text button confirm
      cancelLabel: 'Cancel',                             // Text button cancel
      onConfirm: () => { console.log('a'); }
    });

**Comment by alex6633** [comment]
@GA-MO 
Is there a way that I can prevent the layer behind my alert box from scrolling ?
