### ISSUE TITLE
"closeOnClickOutside" does not work with customUI

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [GA-MO/react-confirm-alert#30]
I have used confirm alert in my application and want to disable outside click. ie user should not be able to click on outside of the confirm pop-up and should not close. Users have to explicitly use the button in alert to close pop-up.

But this is not working and users are still able to click outside to close pop-up.
```jsx
       confirmAlert({
            customUI: ({ onClose }) => {
                return (
                    <div className='custom-confirm-ui'>
                        <div className='text-left'>
                            <p>test</p>
                        </div>
                        <button className="btn btn-cn btn-secondary" autoFocus="true" onClick={() => {
                            this.forceUpdate();
                            onClose();
                        }}> Ok </button>
                    </div>
                )
            },
            closeOnClickOutside: false
        })
```

**Comment by GA-MO** [comment]
@AbhaysinghBhosale 
Your code is working! [Try this demo](https://stackblitz.com/edit/react-8en5ut)
Try update package to the latest version

**Comment by AbhaysinghBhosale** [comment]
@GA-MO thanks for information, i did updated packages to latest version and its worked fine. Thanks
