### ISSUE TITLE
No buttons or styling

### ISSUE THREAD

**Issue by z-sanjivini** [GA-MO/react-confirm-alert#49]
`import { confirmAlert } from 'react-confirm-alert'; // Import
import 'react-confirm-alert/src/react-confirm-alert.css'

/** Importing custom Components */

import { setCurrentResponse, removeResponse } from "../../../store/actions/rules/rulesActions";

/** Importing custom Styles */
import classes from './RulesResponses.module.css';
import PlayIcon from '../../UI/PlayIcon/PlayIcon';
import AlertModal from '../../UI/AlertModal/AlertModal';

/** Main Components */
const RulesResponses = ({ propsRedux, propsOwned, setCurrentResponse, removeResponse }) => {

    var responsesArr = propsOwned.responsesArr;
    var isAddResponseVisible = propsOwned.isAddResponseVisible;
    const title= "Title";

    const options = {
        title: title,
        message: 'Message',
        buttons: [
          {
            label: 'Yes',
            onClick: () => alert('Click Yes')
          },
          {
            label: 'No',
            onClick: () => alert('Click No')
          }
        ],
        childrenElement: () => <div />,
        customUI: ({ onClose }) => <div>Custom UI</div>,
        closeOnEscape: true,
        closeOnClickOutside: true,
        willUnmount: () => {},
        afterClose: () => {},
        onClickOutside: () => {},
        onKeypressEscape: () => {}
      };

    const _onRemoveClick = (index=0) => {
        confirmAlert(options);
        removeResponse(propsOwned.dataRulekey, propsOwned.evalKey, propsOwned.responseKey, propsOwned.iterationKey, index);
    }`

**Comment by z-sanjivini** [comment]
I do not see any buttons or any styles when I simply try the code given in for demo. I see an overlay with just custom UI written in the centre

**Comment by Johnne25** [comment]
I had the same issue.
No style applied using the code provided in the samples.

**Comment by GA-MO** [comment]
@z-sanjivini @Johnne25 
Remove `customUI: ({ onClose }) => <div>Custom UI</div>` out of the options for simple test.
