### ISSUE TITLE
Please export the static close method

### ISSUE THREAD

**Issue by jcalfee** [GA-MO/react-confirm-alert#5]
https://github.com/GA-MO/react-confirm-alert/blob/master/src/index.js#L37-L43

This would be useful in a react dumb component (without state) where `confirmAlert` was used to show the dialog.

**Comment by jcalfee** [comment]
Be aware that if the dialog is already close the method should probably not error.  I would recommend to return true if you found the root node and closed it but false if the dialog was not found in the DOM. 

```js
function reactConfirmClose() {
  const target = document.getElementById('react-confirm-alert');
  if(!target) {
    return false
  }
  const svg = document.getElementById('react-confirm-alert-firm-svg');
  target.parentNode.removeChild(target);
  svg.parentNode.removeChild(svg);
  const root = document.body.children[0];
  root.classList.remove('react-confirm-alert-blur');
  return true
}
```

**Comment by jcalfee** [comment]
I believe this close logic is denying childrenElement their react life cycle events.

If I use an embedded QrReader (react-qr-reader) this close method leaves the camera on.  If include the QrReader directly in render then the component gets removed via a higher level react condition, the camera does turn off.

**Comment by GA-MO** [comment]
Can you please create PR to solve this?

**Comment by GA-MO** [comment]
Solve this in version 2 use option `willUnmount`
