### ISSUE TITLE
Close confirm alert 

### ISSUE THREAD

**Issue by vasu-tamrakar** [GA-MO/react-confirm-alert#57]
I have opened confirm alert, then I have clicked on browser go back button. then should be close alert popup on next page. now  showing confirm alert popup on other page. I want to only same page. how to manage this.

**Comment by GA-MO** [comment]
@vasu-tamrakar 
You can use `componentWillUnmount ` to close the confirm alert.
This lifecycle will call when the page unmount and yes (click browser go back button) as well.
