### ISSUE TITLE
Button ordering

### ISSUE THREAD

**Issue by mribbons** [GA-MO/react-confirm-alert#7]
Is it possible to have display confirm button before cancel button?

I know I can do this by swapping the order in the code, eg:

```js
confirmAlert({
    title: 'Confirm',                        // Title dialog
    message: `Are you sure?`,               // Message dialog
    confirmLabel: 'No',                           // Text button confirm
    cancelLabel: 'Yes',                             // Text button cancel
});
```

But it feels messy.

**Comment by BhavikModi** [comment]
@mribbons do you have any solution on this?

**Comment by mribbons** [comment]
@BhavikModi nope, probably the solution is to clone to a new repo and make changes. I don't see the original devs breaking their code.

**Comment by GA-MO** [comment]
Solve this in version 2
