### ISSUE TITLE
Upgrade to React18?

### ISSUE THREAD

**Issue by vova42matters** [GA-MO/react-confirm-alert#74]
ReactDOM now uses a bit different structure for render and unmountComponentAtNode. When using react-confirm-alert with React18 an error gets thrown

**Comment by ergisgjergji** [comment]
@vova42matters I have opened a PR for this. But until it's merged, you can use [@ergisgjergji/react-chat-plugin](https://www.npmjs.com/package/@ergisgjergji/react-confirm-alert): I published it as my own because I needed to use it ASAP and who knows when the PR will be merged...

**Comment by vova42matters** [comment]
@GA-MO #75

**Comment by Aravin** [comment]
I am getting the following error

File '.../node_modules/@ergisgjergji/react-confirm-alert/index.d.ts' is not a module.ts(2306)

when I install npm package from your repo https://www.npmjs.com/package/@ergisgjergji/react-confirm-alert

**Comment by Aravin** [comment]
Even if I ignore this error

getting this error while calling the delete fn 

`next-dev.js?3515:25 Warning: You are calling ReactDOMClient.createRoot() on a container that was previously passed to ReactDOM.render(). This is not supported.`

**Comment by ergisgjergji** [comment]
@Aravin can't say much. I've installed/used it on different PC's now. Maybe try `npm i --force`. As for the warning: maybe you are doing a double-call of `confirmAlert`. As per the 2nd error, can you provide some short code how you are calling it / which props are you using?

**Comment by Aravin** [comment]
I no longer use that `react-confirm-alert`.

**Comment by GA-MO** [comment]
Version 3.0.0 is out for support React 18.

**Comment by vova42matters** [comment]
@GA-MO Thanks!
