### ISSUE TITLE
Module not found: Can't resolve 'react-dom/client

### ISSUE THREAD

**Issue by viveleroi** [GA-MO/react-confirm-alert#80]
Installed this module in a NextJS 12/React v17 project and am getting the following error:

```
./node_modules/react-confirm-alert/lib/index.js:24:0
Module not found: Can't resolve 'react-dom/client'
```

Is v3 *only* for React 18? I can't find documentation or proper changelogs.

**Comment by NastyaSid** [comment]
The same for me...

**Comment by GA-MO** [comment]
Document updated.
For react <= 17.x.x use version 2.x.x
